<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegionDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            ['region' => 'Western',     'district' => 'Jomoro Municipal'],
            ['region' => 'Western',     'district' => 'Ellembelle'],
            ['region' => 'Western',     'district' => 'Nzema East Municipal'],
            ['region' => 'Western',     'district' => 'Ahanta West Municipal'],
            ['region' => 'Western',     'district' => 'Effia Kwesimintsim Municipal'],
            ['region' => 'Western',     'district' => 'Sekondi Takoradi Metropolitan Area (STMA)'],
            ['region' => 'Western',     'district' => 'Shama'],
            ['region' => 'Western',     'district' => 'Wassa East'],
            ['region' => 'Western',     'district' => 'Mpohor'],
            ['region' => 'Western',     'district' => 'Tarkwa-Nsuaem Municipal'],
            ['region' => 'Western',     'district' => 'Prestea/Huni Valley Municipal'],
            ['region' => 'Western',     'district' => 'Wassa Amenfi East Municipal'],
            ['region' => 'Western',     'district' => 'Wassa Amenfi Central'],
            ['region' => 'Western',     'district' => 'Wassa Amenfi West Municipal'],
            ['region' => 'Central', 'district' => 'Komenda Edina Eguafo Abirem Municipal'],
            ['region' => 'Central', 'district' => 'Cape Coast Metropolitan Area (CCMA)'],
            ['region' => 'Central', 'district' => 'Abura Asebu Kwamankese'],
            ['region' => 'Central', 'district' => 'Mfantsiman Municipal'],
            ['region' => 'Central', 'district' => 'Ekumfi'],
            ['region' => 'Central', 'district' => 'Gomoa West'],
            ['region' => 'Central', 'district' => 'Effutu Municipal'],
            ['region' => 'Central', 'district' => 'Gomoa Central'],
            ['region' => 'Central', 'district' => 'Gomoa East'],
            ['region' => 'Central', 'district' => 'Awutu Senya East Municipal'],
            ['region' => 'Central', 'district' => 'Awutu Senya'],
            ['region' => 'Central', 'district' => 'Agona East'],
            ['region' => 'Central', 'district' => 'Agona West Municipal'],
            ['region' => 'Central', 'district' => 'Asikuma Odoben Brakwa'],
            ['region' => 'Central', 'district' => 'Ajumako Enyan Essiam'],
            ['region' => 'Central', 'district' => 'Assin South'],
            ['region' => 'Central', 'district' => 'Twifo Heman Lower Denkyira'],
            ['region' => 'Central', 'district' => 'Twifo Ati Morkwa'],
            ['region' => 'Central', 'district' => 'Assin Fosu Municipal'],
            ['region' => 'Central', 'district' => 'Assin North'],
            ['region' => 'Central', 'district' => 'Upper Denkyira East Municipal'],
            ['region' => 'Central', 'district' => 'Upper Denkyira West'],
            ['region' => 'Accra', 'district' => 'Ga South Municipal'],
            ['region' => 'Accra', 'district' => 'Weija Gbawe Municipal'],
            ['region' => 'Accra', 'district' => 'Ga Central Municipal'],
            ['region' => 'Accra', 'district' => 'Ablekuma North Municipal'],
            ['region' => 'Accra', 'district' => 'Ablekuma West Municipal'],
            ['region' => 'Accra', 'district' => 'Ablekuma Central Municipal'],
            ['region' => 'Accra', 'district' => 'Accra Metropolitan Area (AMA)'],
            ['region' => 'Accra', 'district' => 'Korle Klottey Municipal'],
            ['region' => 'Accra', 'district' => 'Ayawaso Central Municipal'],
            ['region' => 'Accra', 'district' => 'Ayawaso East Municipal'],
            ['region' => 'Accra', 'district' => 'Ayawaso North Municipal'],
            ['region' => 'Accra', 'district' => 'La Dade-Kotopon Municipal'],
            ['region' => 'Accra', 'district' => 'Ledzokuku Municipal'],
            ['region' => 'Accra', 'district' => 'Krowor Municipal'],
            ['region' => 'Accra', 'district' => 'Adentan Municipal'],
            ['region' => 'Accra', 'district' => 'Ayawaso West Municipal'],
            ['region' => 'Accra', 'district' => 'Okaikoi North Municipal'],
            ['region' => 'Accra', 'district' => 'Ga North Municipal'],
            ['region' => 'Accra', 'district' => 'Ga West Municipal'],
            ['region' => 'Accra', 'district' => 'Ga East Municipal'],
            ['region' => 'Accra', 'district' => 'La Nkwantanang Madina Municipal'],
            ['region' => 'Accra', 'district' => 'Kpone Katamanso Municipal'],
            ['region' => 'Accra', 'district' => 'Ashaiman Municipal'],
            ['region' => 'Accra', 'district' => 'Tema West Municipal'],
            ['region' => 'Accra', 'district' => 'Tema Metropolitan Area (TMA)'],
            ['region' => 'Accra', 'district' => 'Ningo-Prampram'],
            ['region' => 'Accra', 'district' => 'Shai-Osudoku'],
            ['region' => 'Accra', 'district' => 'Ada West'],
            ['region' => 'Accra', 'district' => 'Ada East'],
            ['region' => 'Volta', 'district' => 'South Tongu'],
            ['region' => 'Volta', 'district' => 'Anloga'],
            ['region' => 'Volta', 'district' => 'Keta Municipal'],
            ['region' => 'Volta', 'district' => 'Ketu South Municipal'],
            ['region' => 'Volta', 'district' => 'Ketu North Municipal'],
            ['region' => 'Volta', 'district' => 'Akatsi North'],
            ['region' => 'Volta', 'district' => 'Akatsi South Municipal'],
            ['region' => 'Volta', 'district' => 'Central Tongu'],
            ['region' => 'Volta', 'district' => 'North Tongu'],
            ['region' => 'Volta', 'district' => 'Ho West'],
            ['region' => 'Volta', 'district' => 'Adaklu'],
            ['region' => 'Volta', 'district' => 'Agortime-Ziope'],
            ['region' => 'Volta', 'district' => 'Ho Municipal'],
            ['region' => 'Volta', 'district' => 'South Dayi'],
            ['region' => 'Volta', 'district' => 'Afadzato South'],
            ['region' => 'Volta', 'district' => 'North Dayi'],
            ['region' => 'Volta', 'district' => 'Kpando Municipal'],
            ['region' => 'Volta', 'district' => 'Hohoe Municipal'],
            ['region' => 'Eastern', 'district' => 'Birim South'],
            ['region' => 'Eastern', 'district' => 'Birim Central Municipal'],
            ['region' => 'Eastern', 'district' => 'Achiase'],
            ['region' => 'Eastern', 'district' => 'Asene Manso Akroso'],
            ['region' => 'Eastern', 'district' => 'West Akim Municipal'],
            ['region' => 'Eastern', 'district' => 'Upper West Akim'],
            ['region' => 'Eastern', 'district' => 'Ayensuano'],
            ['region' => 'Eastern', 'district' => 'Nsawam Adoagyiri Municipal'],
            ['region' => 'Eastern', 'district' => 'Akwapim South Municipal'],
            ['region' => 'Eastern', 'district' => 'Akwapim North Municipal'],
            ['region' => 'Eastern', 'district' => 'Okere'],
            ['region' => 'Eastern', 'district' => 'New Juaben South Municipal'],
            ['region' => 'Eastern', 'district' => 'New Juaben North Municipal'],
            ['region' => 'Eastern', 'district' => 'Suhum Municipal'],
            ['region' => 'Eastern', 'district' => 'Abuakwa North Municipal'],
            ['region' => 'Eastern', 'district' => 'Abuakwa South Municipal'],
            ['region' => 'Eastern', 'district' => 'Denkyembuor'],
            ['region' => 'Eastern', 'district' => 'Akyemansa'],
            ['region' => 'Eastern', 'district' => 'Kwaebibirem Municipal'],
            ['region' => 'Eastern', 'district' => 'Birim North'],
            ['region' => 'Eastern', 'district' => 'Atiwa West'],
            ['region' => 'Eastern', 'district' => 'Atiwa East'],
            ['region' => 'Eastern', 'district' => 'Fanteakwa South'],
            ['region' => 'Eastern', 'district' => 'Yilo Krobo Municipal'],
            ['region' => 'Eastern', 'district' => 'Lower Manya Krobo Municipal'],
            ['region' => 'Eastern', 'district' => 'Asuogyaman'],
            ['region' => 'Eastern', 'district' => 'Upper Manya Krobo'],
            ['region' => 'Eastern', 'district' => 'Fanteakwa North'],
            ['region' => 'Eastern', 'district' => 'Kwahu South Municipal'],
            ['region' => 'Eastern', 'district' => 'Kwahu West Municipal'],
            ['region' => 'Eastern', 'district' => 'Kwahu East'],
            ['region' => 'Eastern', 'district' => 'Kwahu Afram Plains South'],
            ['region' => 'Eastern', 'district' => 'Kwahu Afram Plains North'],
            ['region' => 'Ashanti', 'district' => 'Amansie South'],
            ['region' => 'Ashanti', 'district' => 'Amansie Central'],
            ['region' => 'Ashanti', 'district' => 'Akrofuom'],
            ['region' => 'Ashanti', 'district' => 'Adansi South'],
            ['region' => 'Ashanti', 'district' => 'Adansi Asokwa'],
            ['region' => 'Ashanti', 'district' => 'Obuasi East'],
            ['region' => 'Ashanti', 'district' => 'Obuasi Municipal'],
            ['region' => 'Ashanti', 'district' => 'Adansi North'],
            ['region' => 'Ashanti', 'district' => 'Bekwai Municipal'],
            ['region' => 'Ashanti', 'district' => 'Amansie West'],
            ['region' => 'Ashanti', 'district' => 'Atwima Kwanwoma'],
            ['region' => 'Ashanti', 'district' => 'Bosomtwi'],
            ['region' => 'Ashanti', 'district' => 'Bosome Freho'],
            ['region' => 'Ashanti', 'district' => 'Asante Akim Central Municipal'],
            ['region' => 'Ashanti', 'district' => 'Asante Akim South Municipal'],
            ['region' => 'Ashanti', 'district' => 'Asante Akim North Municipal'],
            ['region' => 'Ashanti', 'district' => 'Sekyere Kumawu'],
            ['region' => 'Ashanti', 'district' => 'Sekyere East'],
            ['region' => 'Ashanti', 'district' => 'Juaben Municipal'],
            ['region' => 'Ashanti', 'district' => 'Ejisu Municipal'],
            ['region' => 'Ashanti', 'district' => 'Oforikrom Municipal'],
            ['region' => 'Ashanti', 'district' => 'Asokwa Municipal'],
            ['region' => 'Ashanti', 'district' => 'Kumasi Metropolitan Area (KMA)'],
            ['region' => 'Ashanti', 'district' => 'Kwadaso Municipal'],
            ['region' => 'Ashanti', 'district' => 'Suame Municipal'],
            ['region' => 'Ashanti', 'district' => 'Old Tafo Municipal'],
            ['region' => 'Ashanti', 'district' => 'Asokore Mampong Municipal'],
            ['region' => 'Ashanti', 'district' => 'Kwabre East'],
            ['region' => 'Ashanti', 'district' => 'Afigya Kwabre South'],
            ['region' => 'Ashanti', 'district' => 'Atwima Nwabiagya North'],
            ['region' => 'Ashanti', 'district' => 'Atwima Nwabiagya South Municipal'],
            ['region' => 'Ashanti', 'district' => 'Atwima Mponua'],
            ['region' => 'Ashanti', 'district' => 'Ahafo Ano South West'],
            ['region' => 'Ashanti', 'district' => 'Ahafo Ano North Municipal'],
            ['region' => 'Ashanti', 'district' => 'Ahafo Ano South East'],
            ['region' => 'Ashanti', 'district' => 'Offinso North'],
            ['region' => 'Ashanti', 'district' => 'Offinso Municipal'],
            ['region' => 'Ashanti', 'district' => 'Afigya Kwabre North'],
            ['region' => 'Ashanti', 'district' => 'Sekyere South'],
            ['region' => 'Ashanti', 'district' => 'Mampong Municipal'],
            ['region' => 'Ashanti', 'district' => 'Ejura Sekyedumase Municipal'],
            ['region' => 'Ashanti', 'district' => 'Sekyere Central'],
            ['region' => 'Ashanti', 'district' => 'Sekyere Afram Plains'],
            ['region' => 'Western North', 'district' => 'Aowin Municipal'],
            ['region' => 'Western North', 'district' => 'Sefwi Akontombra'],
            ['region' => 'Western North', 'district' => 'Suaman'],
            ['region' => 'Western North', 'district' => 'Bodi'],
            ['region' => 'Western North', 'district' => 'Sefwi Wiawso Municipal'],
            ['region' => 'Western North', 'district' => 'Bibiani Anhwiaso Bekwai Municipal'],
            ['region' => 'Western North', 'district' => 'Juaboso'],
            ['region' => 'Western North', 'district' => 'Bia West'],
            ['region' => 'Western North', 'district' => 'Bia East'],
            ['region' => 'Western North', 'district' => 'Aowin Municipal'],
            ['region' => 'Western North', 'district' => 'Sefwi Akontombra'],
            ['region' => 'Western North', 'district' => 'Suaman'],
            ['region' => 'Western North', 'district' => 'Bodi'],
            ['region' => 'Western North', 'district' => 'Sefwi Wiawso Municipal'],
            ['region' => 'Western North', 'district' => 'Bibiani Anhwiaso Bekwai Municipal'],
            ['region' => 'Western North', 'district' => 'Juaboso'],
            ['region' => 'Western North', 'district' => 'Bia West'],
            ['region' => 'Western North', 'district' => 'Bia East'],
            ['region' => 'Ahafo', 'district' => 'Asunafo South'],
            ['region' => 'Ahafo', 'district' => 'Asunafo North Municipal'],
            ['region' => 'Ahafo', 'district' => 'Asutifi South'],
            ['region' => 'Ahafo', 'district' => 'Asutifi North'],
            ['region' => 'Ahafo', 'district' => 'Tano North Municipal'],
            ['region' => 'Ahafo', 'district' => 'Tano South Municipal'],
            ['region' => 'Bono', 'district' => 'Dormaa West'],
            ['region' => 'Bono', 'district' => 'Dormaa Central Municipal'],
            ['region' => 'Bono', 'district' => 'Dormaa East'],
            ['region' => 'Bono', 'district' => 'Sunyani Municipal'],
            ['region' => 'Bono', 'district' => 'Sunyani West Municipal'],
            ['region' => 'Bono', 'district' => 'Berekum East Municipal'],
            ['region' => 'Bono', 'district' => 'Berekum West'],
            ['region' => 'Bono', 'district' => 'Jaman South'],
            ['region' => 'Bono', 'district' => 'Jaman North'],
            ['region' => 'Bono', 'district' => 'Tain'],
            ['region' => 'Bono', 'district' => 'Wenchi Municipal'],
            ['region' => 'Bono', 'district' => 'Banda'],
            ['region' => 'Bono East', 'district' => 'Nkoranza South Municipal'],
            ['region' => 'Bono East', 'district' => 'Techiman Municipal'],
            ['region' => 'Bono East', 'district' => 'Nkoranza North'],
            ['region' => 'Bono East', 'district' => 'Techiman North'],
            ['region' => 'Bono East', 'district' => 'Atebubu Amantin Municipal'],
            ['region' => 'Bono East', 'district' => 'Sene West'],
            ['region' => 'Bono East', 'district' => 'Sene East'],
            ['region' => 'Bono East', 'district' => 'Pru West'],
            ['region' => 'Bono East', 'district' => 'Pru East'],
            ['region' => 'Bono East', 'district' => 'Kintampo South'],
            ['region' => 'Bono East', 'district' => 'Kintampo North Municipal'],
            ['region' => 'Oti', 'district' => 'Biakoye'],
            ['region' => 'Oti', 'district' => 'Jasikan Municipal'],
            ['region' => 'Oti', 'district' => 'Kadjebi'],
            ['region' => 'Oti', 'district' => 'Krachi East Municipal'],
            ['region' => 'Oti', 'district' => 'Krachi West Municipal'],
            ['region' => 'Oti', 'district' => 'Krachi Nchumuru'],
            ['region' => 'Oti', 'district' => 'Nkwanta South Municipal'],
            ['region' => 'Oti', 'district' => 'Nkwanta North (Kpassa)'],
            ['region' => 'Oti', 'district' => 'Guan'],
            ['region' => 'Northern', 'district' => 'Kpandai'],
            ['region' => 'Northern', 'district' => 'Nanumba South'],
            ['region' => 'Northern', 'district' => 'Nanumba North Municipal'],
            ['region' => 'Northern', 'district' => 'Zabzugu'],
            ['region' => 'Northern', 'district' => 'Tatale Sanguli'],
            ['region' => 'Northern', 'district' => 'Saboba'],
            ['region' => 'Northern', 'district' => 'Yendi Municipal'],
            ['region' => 'Northern', 'district' => 'Mion'],
            ['region' => 'Northern', 'district' => 'Nanton'],
            ['region' => 'Northern', 'district' => 'Tamale Metropolitan Area (TMA)'],
            ['region' => 'Northern', 'district' => 'Sagnarigu Municipal'],
            ['region' => 'Northern', 'district' => 'Tolon'],
            ['region' => 'Northern', 'district' => 'Kumbungu'],
            ['region' => 'Northern', 'district' => 'Savelugu Municipal'],
            ['region' => 'Northern', 'district' => 'Karaga'],
            ['region' => 'Northern', 'district' => 'Gushegu Municipal'],
            ['region' => 'Savannah', 'district' => 'Bole'],
            ['region' => 'Savannah', 'district' => 'Sawla Tuna Kalba'],
            ['region' => 'Savannah', 'district' => 'North Gonja'],
            ['region' => 'Savannah', 'district' => 'West Gonja'],
            ['region' => 'Savannah', 'district' => 'Central Gonja'],
            ['region' => 'Savannah', 'district' => 'East Gonja Municipal'],
            ['region' => 'Savannah', 'district' => 'North East Gonja'],
            ['region' => 'North East', 'district' => 'Mamprugu Moagduri'],
            ['region' => 'North East', 'district' => 'West Mamprusi Municipal'],
            ['region' => 'North East', 'district' => 'East Mamprusi Municipal'],
            ['region' => 'North East', 'district' => 'Bunkpurugu Nakpanduri'],
            ['region' => 'North East', 'district' => 'Yunyoo Nasuan'],
            ['region' => 'North East', 'district' => 'Chereponi'],
            ['region' => 'Upper East', 'district' => 'Builsa South'],
            ['region' => 'Upper East', 'district' => 'Builsa North Municipal'],
            ['region' => 'Upper East', 'district' => 'Kasena Nankana Municipal'],
            ['region' => 'Upper East', 'district' => 'Kasena Nankana West'],
            ['region' => 'Upper East', 'district' => 'Bolgatanga Municipal'],
            ['region' => 'Upper East', 'district' => 'Talensi'],
            ['region' => 'Upper East', 'district' => 'Bolgatanga East'],
            ['region' => 'Upper East', 'district' => 'Bongo'],
            ['region' => 'Upper East', 'district' => 'Nabdam'],
            ['region' => 'Upper East', 'district' => 'Bawku West'],
            ['region' => 'Upper East', 'district' => 'Binduri'],
            ['region' => 'Upper East', 'district' => 'Bawku Municipal'],
            ['region' => 'Upper East', 'district' => 'Garu'],
            ['region' => 'Upper East', 'district' => 'Tempane'],
            ['region' => 'Upper East', 'district' => 'Pusiga'],
            ['region' => 'Upper West', 'district' => 'Wa West'],
            ['region' => 'Upper West', 'district' => 'Wa East'],
            ['region' => 'Upper West', 'district' => 'Wa Municipal'],
            ['region' => 'Upper West', 'district' => 'Nadowli Kaleo'],
            ['region' => 'Upper West', 'district' => 'Daffiama Bussie Issa'],
            ['region' => 'Upper West', 'district' => 'Sissala East Municipal'],
            ['region' => 'Upper West', 'district' => 'Sissala West'],
            ['region' => 'Upper West', 'district' => 'Jirapa Municipal'],
            ['region' => 'Upper West', 'district' => 'Lawra Municipal'],
            ['region' => 'Upper West', 'district' => 'Lambussie Karni'],
            ['region' => 'Upper West', 'district' => 'Nandom'],
        ];
        DB::table('region_districts')->insert($data);
    }
}
